# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'parties'},
        ),
    ]
