# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20170806_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='StateInfo',
        ),
    ]
