# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_absenteetype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenteetype',
            name='days_prior',
            field=models.IntegerField(default=0),
        ),
    ]
