# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_absenteetype_days_prior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absenteetype',
            name='description',
        ),
        migrations.AddField(
            model_name='absenteetype',
            name='election_type',
            field=models.CharField(default='GENERAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='absenteetype',
            name='days_prior',
            field=models.IntegerField(default=0, help_text='Number days prior to election when requests can be made'),
        ),
    ]
