# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_auto_20170807_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenteeExceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Generic name used to define a new exception', max_length=20)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenteeRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Generic name used to define a new rule', max_length=20)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='StateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(help_text='Enter state abbreviation', max_length=2)),
                ('name_long', models.CharField(help_text='Enter state name', max_length=30)),
                ('can_vote_by_mail', models.BooleanField(default=False)),
                ('absentee_rules', models.ManyToManyField(help_text='Select the absentee rules for this state', to='vote.AbsenteeRules')),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='absentee_type',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('HOME_1', 'Primary home'), ('HOME_2', 'Secondary home'), ('MAILING_1', 'Primary mailing'), ('MAILING_2', 'Secondary mailing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.DeleteModel(
            name='AbsenteeType',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
