# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_auto_20170809_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stateinfo',
            options={'verbose_name_plural': 'state info'},
        ),
        migrations.RemoveField(
            model_name='absenteeexception',
            name='type',
        ),
        migrations.RemoveField(
            model_name='absenteerule',
            name='type',
        ),
        migrations.AddField(
            model_name='absenteeexception',
            name='name',
            field=models.CharField(default='', help_text='Generic name used in forms', max_length=20),
        ),
        migrations.AddField(
            model_name='absenteerule',
            name='name',
            field=models.CharField(default='', help_text='Generic name used in forms', max_length=20),
        ),
    ]
