# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0014_auto_20170809_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='exceptions',
            field=models.ManyToManyField(blank=True, help_text='Select the absentee exceptions for this user (based on state)', to='vote.StateException'),
        ),
    ]
